### PR TITLE
feat: add content-based redirection for Renku entities

### LINKED ISSUE #174: Set up content-based redirections
Requests to URIs identifying a Renku entity should be routed to the gateway and then result in a redirection to the UI page or the corresponding API endpoint depending on the `Accept` header.

- [x] Modify ingress rule to serve gateway also under the ~Renku base URL~ `/entities`.
- [x] Add two routers based on header rules each combined with a redirectRegex middleware to achieve the 
```
text/html -> UI
application/json or application/ld+json -> API
```
redirections.

See also the discussion on https://github.com/SwissDataScienceCenter/renku-gateway/issues/169 for details.

### PR DESCRIPTION
**Pull request by ableuler**
closes #174.

Currently deployed under https://andreas.dev.renku.ch

### CODE REVIEW

**Comment by rokroskar** [comment]
This hangs: 

```
curl 'https://andreas.dev.renku.ch/entities/datasets/7dfb68f5-3925-470a-91ce-7eb81fe0d60e' -H 'Accept: application/json'
```
is there something else missing?

**Comment by ableuler** [comment]
> This hangs:
> 
> ```
> curl 'https://andreas.dev.renku.ch/entities/datasets/7dfb68f5-3925-470a-91ce-7eb81fe0d60e' -H 'Accept: application/json'
> ```
> 
> is there something else missing?

Should work now...

**Comment by rokroskar** [comment]
it redirects me to 

```
https://andreas.dev.renku.ch/api/datasets/7dfb68f5-3925-470a-91ce-7eb81fe0d60e
```

Shouldn't it go to `/knowledge-graph/datasets/<id>`?

**Comment by ableuler** [comment]
> it redirects me to
> 
> ```
> https://andreas.dev.renku.ch/api/datasets/7dfb68f5-3925-470a-91ce-7eb81fe0d60e
> ```
> 
> Shouldn't it go to `/knowledge-graph/datasets/<id>`?

No, I think we've agreed to start with projects for the time being. Content negotiation / redirection for datasets should work as soon as they are exposed through the gateway as `api/datasets`.

**Comment by rokroskar** [comment]
Oh really? I thought we agreed to do datasets first :) 

@jachro the `/knowledge-graph/projects` endpoint expects a project ID? I get: 

```
curl https://andreas.dev.renku.ch/knowledge-graph/projects/rokroskar/test
{"message":"No 'rokroskar/test' project found"}
```

**Comment by jachro** [comment]
No, the project endpoint requires `name` and `namespace` (`GET /knowledge-graph/projects/:namespace/:name`)

By the way, I also thought we are going to start with `/datasets`.

**Comment by ableuler** [comment]
> Oh really? I thought we agreed to do datasets first :)

I don't think I would have consciously agreed to that :) The dataset query should - in my opinion - be routed through the gateway anyway. For this we need to agree on how we handle authentication between gateway and graph service. Once this is in place, the content negotiation / redirection as proposed by this PR will work for datasets too.

**Comment by jachro** [comment]
Cool! I'm fine with that.

**Comment by jachro** [comment]
In terms of the `rokroskar/test` it looks the KG is not enabled for it on Andreas's env.

**Comment by rokroskar** [comment]
But now you will have two hops? First, `/entities --> /api` and then `/api --> /knowledge-graph`? This seems a bit much?

**Comment by ableuler** [comment]
> But now you will have two hops? First, `/entities --> /api` and then `/api --> /knowledge-graph`? This seems a bit much?

The first is a redirection, the second a forwarding. I think this is perfectly fine.

**Comment by ableuler** [comment]
Ok, I've added the forwarding for the datasets on to the gateway, now the redirections work for the datasets too. Let's try to address the (remaining) first checklist item of https://github.com/SwissDataScienceCenter/renku-gateway/issues/175 as soon as possible too.

**Comment by rokroskar** [comment]
Yes! then we can access the API securely from the CLI.

**Pull request merged**
