### PR TITLE
493 gitlab urls

### PR DESCRIPTION
**Pull request by lorenzo-cavazzi**
It turns out that streamlining the logic to handle the GitLab prefix with trailing slashes is not that simple.
The main reason is the impossibility to chain multiple `addPrefix` where one returns an empty string. Also, a `/` is automatically added as the first char if it's not already there.

I also tried with a different approach, using `ReplacePathRegex` instead of multiple `addPrefix`, but that seems to fail on some project paths containing the `/` char -- it's the last version pushed in this PR.

We either need to:
- keep a few `if` here and there, but then we don't really simplify compared to the current solution
- or require to specify the full GitLab URL in the values file.

The last seems (by far) the most reasonable solution. Looking at values files, it seems that having a separate `urlPrefix` is not really useful. And we pass the full GitLab URL also as values local to other charts.
Am I missing some use for the `urlPrefix`, or is it possible it's just a leftover from the old days? Should we consider adding something like `global.gitlab.url` and removing it from the other places?

re #493

### CODE REVIEW

**Comment by ableuler** [comment]
totally agree, global full gitlab URL is the way to go. I think the days when gitlab will be deployed as part of the Renku chart are counted anyway.

**Comment by rokroskar** [comment]
@lorenzo-cavazzi what is the status here?

**Comment by lorenzo-cavazzi** [comment]
Oh, I missed the ping on this!

@rokroskar I could give it another look if it's still relevant -- it was mainly a cleanup on the traefik routing. I'm not sure if we should wait to discuss the recent idea of unifying the values (that might have an impact here) or if we won't go down that road anyway

**Comment by rokroskar** [comment]
I think specifying the full GitLab URL makes sense. Not sure whether the prefix is used or useful still anywhere.

**Comment by olevski** [comment]
@lorenzo-cavazzi I am pretty sure we can fully close this PR?

**Pull request closed without merging**
