### PR TITLE
Route requests to the uiservice

### PR DESCRIPTION
**Pull request by ciyer**
The changes necessary to allow communication with the uiservice.

### CODE REVIEW

**Comment by ableuler** [comment]
This looks good - the path under which the new service will be exposed and the authentication methods are still open for me but can be adapted easily once https://github.com/swissdatasciencecenter/renku-ui/issues/1043 is merged.

**Comment by ableuler** [comment]
Understanding the functionality and scope of the new ui server (as a general server-side component or the UI, potentially handling sessions, persist UI state, etc) I'd suggest to expose that service at the ingress level and not behind the `/api`(ie not through the gateway).

**Comment by ciyer** [comment]
> Understanding the functionality and scope of the new ui server (as a general server-side component or the UI, potentially handling sessions, persist UI state, etc) I'd suggest to expose that service at the ingress level and not behind the `/api`(ie not through the gateway).

That is an interesting proposal. What would that mean for authentication and token management?

**Comment by ableuler** [comment]
I think the easiest would be for the UI service to have its own session with the frontend. We might want to even make this the the _only_ session (ie we would route all API calls from the browser through the UI service), but that would have to be discussed and could follow in a second step.

**Comment by ableuler** [comment]
What's the status here? As mentioned before I would suggest to expose this UI-service directly through an ingress and not as a part of a REST api. Would it be ok to close this issue?

**Comment by lorenzo-cavazzi** [comment]
@ableuler Sorry for addressing this late. If I understand correctly your suggestion, we should drop this PR and add the ingress configuration directly in the Renku repository.
I have made a PR for that. Let me know if that works SwissDataScienceCenter/renku#2025

**Comment by lorenzo-cavazzi** [comment]
Not needed anymore SwissDataScienceCenter/renku#2025

**Pull request closed without merging**
