### PR TITLE
fix ontology definition

### PR DESCRIPTION
**Pull request by rokroskar**
Using `dcterms` is no longer necessary and we are using `schema.org` instead - therefore the graph query needs to be modified.

### CODE REVIEW

**Comment by rokroskar** [comment]
Right, I suppose there should be an `OR` in the query...

**Comment by lorenzo-cavazzi** [comment]
ok, that should be fixed in `renku-graph` since the graph rebuilt is done there, right?

**Comment by rokroskar** [comment]
> ok, that should be fixed in renku-graph since the graph rebuilt is done there, right?

you mean the renku-python version? Yes - but I think for now we can just check for both predicates.

**Comment by rokroskar** [comment]
can you try again? I just pushed a change that should make it work with the old ontology as well.

**Comment by rokroskar** [comment]
Presumably for a short time. This will happen frequently over the next weeks as we converge on a graph that we like unfortunately...

**Pull request merged**
