### PR TITLE
refactor: remove CLI login flow

### PR DESCRIPTION
**Pull request by mohammad-sdsc**
Fixes: #557 

/deploy renku=ableuler-patch-1

### CODE REVIEW

**Comment by mohammad-sdsc** [comment]
Related PRs:
https://github.com/SwissDataScienceCenter/renku/pull/2491
https://github.com/SwissDataScienceCenter/renku-python/pull/2722

**Comment by ableuler** [comment]
Thanks @mohammad-sdsc. As mentioned, I suggest that we park this PR for a bit and have at least one Renku release which supports both CLI login options.

**Review by olevski — APPROVED** [review]
As long as the acceptance tests pass this LGTM.

**Comment by rokroskar** [comment]
part of #566

**Pull request closed without merging**
