### PR TITLE
fix(app): re-initialize keycloak client if needed

### PR DESCRIPTION
**Pull request by olevski**
/deploy #persist

### CODE REVIEW

**Comment by olevski** [comment]
Should address:
- https://sentry.dev.renku.ch/organizations/sentry/issues/200/?environment=renkulab&project=8&query=is%3Aunresolved
- https://sentry.dev.renku.ch/organizations/sentry/issues/183/?environment=renkulab&project=8&query=is%3Aunresolved

**Comment by lorenzo-cavazzi** [comment]
The code looks good :+1: 
Any way I can easily reproduce the faulty behavior(s) manually to verify whether the PR fixes it?

**Review by mohammad-sdsc — APPROVED** [review]
Thank you!

**Comment by olevski** [comment]
@lorenzo-cavazzi you can reproduce the behaviour by logging into renku from 2 different browsers. Then log out from one browser only and see that the other one still works. Doing this on renkulab or dev results in any requests in the remaining logged in browser not working.

**Review by lorenzo-cavazzi — APPROVED** [review]
This works well, thank you!

**Pull request merged**
