### PR TITLE
feat: add core service routing

### LINKED ISSUE #180: Relay calls to core-service through the gateway
The new Renku repository service will need to be exposed through the gateway. My suggestion would be to expose it as `/api/repository/...` which will result in API endpoints such as 
```
https://renkulab.io/api/repository/cache/project-clone
```
To serve such requests, the repository service will need access to the gitlab oauth access token and some user information:
```
Renku-user-id: 9af6abce-bd63-48e4-a0c7-233a8c524e48
Renku-user-fullname: Andreas Bleuler
Renku-user-email: andi@example.com
Authorization: Bearer db6d049ec8f3c225c248fe6f3caddbd47c948edb22e6b83b37cc08d79b264ca1
```
All these will be added to dedicated header fields by the gateway before forwarding the request.

The repository URL (containing gitlab namespace and project name) will be provided by the client as part of the request body:
```
{
  "project_url": "https://dev.renku.ch/gitlab/andreas/coffee-machine"
}
```

### PR DESCRIPTION
**Pull request by rokroskar**
- [x] add traefik routes for the core service
- [x] add the required renku-user headers (see #180)

closes #180

### CODE REVIEW

**Comment by rokroskar** [comment]
I think the main thing to decide is what to call the routes. Right now it's `/core` but `/renku` has been suggested.

**Comment by ableuler** [comment]
> I think the main thing to decide is what to call the routes. Right now it's `/core` but `/renku` has been suggested.

Would it be possible to 
1. Make the distinction between RPC and REST a bit clearer in the URL. For me this would mean that RPC endpoints ideally remain "flat".
2. Choose the correct backend service based on the resource in the case of REST (we're already doing this) or the desired action in the case of RPC. Very likely all RPC endpoints would be handled by the `renku-core` service.  

So instead of 
```
https://renkulab.io/api/core/datasets/create
```
we'd have
```
https://renkulab.io/api/createDataset.
```

**Comment by rokroskar** [comment]
But then we have to create a route per command? Wouldn't some top-level grouping be useful?

**Comment by ableuler** [comment]
> But then we have to create a route per command? Wouldn't some top-level grouping be useful?

Maybe we can apply some general rule? Something like this:
```
/camelCase => RPC => forward to renku-core
```
But in general you are definitely right: A clear indication about the right backend service already in the URL will make the rules in the gateway much easier. Avoiding this on the other hand would make for nicer URLs and gives us more flexibility to change things internally without breaking the API. Let's say we suddenly want to serve `/projects` from the graph service instead of gitlab. Currently, we can do this without modifying the UI.

**Comment by lorenzo-cavazzi** [comment]
+1 for grouping all the rpc calls (`/api/core/` or `/api/renku/`), but without further mixing in the "rest style" -- so I would prefer `/createDataset` over `/datasets/create`.

The final result would be something like this `https://renkulab.io/api/renku/{function}`

```
https://renkulab.io/api/renku/createDataset
```

**Comment by rokroskar** [comment]
I like this idea @lorenzo-cavazzi - ideally the routes would then also follow the same convention in the service itself. @jsam?

**Comment by ableuler** [comment]
My only small concern with the suggestion of @lorenzo-cavazzi is that if I see `/api/renku`, I would expect to find all renku-specific endpoints there (including graph stuff, notebook servers, etc) and not just rpc endpoints which correspond Renku cli commands.

**Comment by jsam** [comment]
I find having camel case notation mixed in the URL and as method name very un-natural. If we don't like method reference name in the URL it makes more sense then to go for full jsonrpc 2.0 compliance instead and drop the OpenAPI spec.

**Comment by rokroskar** [comment]
@jsam and I discussed this a bit further - basically at the moment there doesn't seem to be a nice way to automatically generate docs from the code for pure RPC. I propose that we leave the API as is for now, but call it `/renku` instead of `/core`.

**Comment by Panaetius** [comment]
One way I like for urls in this scenario is: `https://renkulab.io/api/renku/dataset.create`

It's still a flat list, the dot has no significance technically, but it helps delineate the methods and it reads like class methods, so it's easy to understand. And doesn't depend on case

**Comment by jsam** [comment]
@Panaetius Done. Service will work with dot-based naming schema for methods. 

I think we can conclude this discussion and merge this.

**Pull request merged**
