### PR TITLE
Use black formatting

### PR DESCRIPTION
**Pull request by ableuler**

### CODE REVIEW

**Comment by rokroskar** [comment]
you could also set up a pre-commit hook: https://github.com/SwissDataScienceCenter/renku-notebooks/blob/master/.pre-commit-config.yaml#L2-L6

**Comment by ableuler** [comment]
> Nice! ⚫
> 
> Should we also add [pytest-black](https://pypi.org/project/pytest-black/) and enforce black formatting in the tests with `pytest --black`? Otherwise, the formating wouldn't be mandatory for new PRs.

Thanks @lorenzo-cavazzi. Would you mind adding this to the present PR? 🙏 
I mostly wanted to have a somewhat cleaner state before tackling https://github.com/SwissDataScienceCenter/renku-gateway/issues/192 and now I'm neck-deep inside that.

**Comment by ableuler** [comment]
> you could also set up a pre-commit hook: https://github.com/SwissDataScienceCenter/renku-notebooks/blob/master/.pre-commit-config.yaml#L2-L6

I was wondering about that recently: This requires you to have a system-wide install of black, right? (not that this would be a deal-breaker...)

**Comment by rokroskar** [comment]
@ableuler I run `chartpress` with `pipenv` here: https://github.com/SwissDataScienceCenter/renku-notebooks/blob/master/.pre-commit-config.yaml#L17 - I'm not sure how it would work with `black`.

**Comment by lorenzo-cavazzi** [comment]
Why is `pytest` now going up to `../../../`? :thinking: 
Has anyone already seen this?

**Comment by lorenzo-cavazzi** [comment]
sorry for forcing, I did (too) many attempts at fixing the failing tests. I didn't manage to limit the scope of `pytest` properly, I can't understand where the issue comes from

**Comment by ableuler** [comment]
@lorenzo-cavazzi your changes seemed all fine to me, there was just a problem with some library not getting installed. I recreated the lockfile which fixed the issue and squashed everything into two commits.

**Pull request merged**
